# https://golangci-lint.run/usage/configuration
version: "2"

linters:
  enable:
    - bodyclose
    - errcheck
    - gocritic
    - gosec
    - govet
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - revive
    - staticcheck
    - unused
  settings:
    revive:
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true

formatters:
  enable:
    - gofmt
    - goimports
    - golines

output:
  formats:
    text:
      print-linter-name: true
      print-issued-lines: true

run:
  timeout: 5m
  tests: true
  concurrency: 4
